package com.mordrum.mdeco.object;

public enum DMPDecorationType {
   barrelLarge,
   barrelSmall,
   benchStone,
   benchWood,
   benchWoodMetalArm,
   cabinetBase,
   cabinetWall,
   cabinetWallGlass,
   capSmallPyramid,
   capLargePyramid,
   capOval,
   capPlus,
   capRound,
   capSquare,
   chain,
   chainLarge,
   chairBasic,
   chairBasicArm,
   chandelierSmallRound,
   coinBag,
   coinStack,
   curioBase,
   curioTop,
   curtainRod,
   curtainWool,
   deskHutchWoodBasic,
   deskWoodBasic,
   endTableMetalRound,
   endTableWood,
   fireplaceBellows,
   fireplacePokerSet,
   fireplaceScreen,
   fireplaceWoodRack,
   foodTrough,
   fountainLava,
   fountainWater,
   ingotStack,
   kitchenKettle,
   kitchenPot,
   kitchenShakers,
   kitchenTableSetting,
   kitchenWallUtensils,
   lanternOval,
   lanternPyramid,
   lanternPyramidGlass,
   lanternRectangle,
   lanternRectangleGlass,
   lanternRound,
   mantle,
   mantleColumn,
   marketCrate,
   marketStand,
   palletStack,
   poleMetal,
   poleMetalConnector,
   poleSign,
   shelf,
   shopSignCornerCut,
   shopSignDome,
   shopSignGable,
   shopSignHexagon,
   shopSignRound,
   shopSignSquare,
   sofa,
   standLargeMetal,
   standLargeStone,
   standSmallMetal,
   standSmallStone,
   standSmallWood,
   supportPole,
   tableWood,
   tile,
   wallLantern,
   waterTrough,
   woodBox,
   woodCrate,
   woodPanel,
   woodTimber,
   woodTimberConnector,
   woodBarkTimber,
   woodBarkTimberConnector,
   woodTrim;

   public float getBoundingWidth() {
      return this == capSmallPyramid?4.0F:(this == capLargePyramid?4.0F:(this == capOval?3.0F:(this == capPlus?4.0F:16.0F)));
   }

   public float getBoundingHeight() {
      return this == capSmallPyramid?8.5F:(this == capLargePyramid?16.0F:(this == capOval?10.0F:(this == capPlus?10.0F:16.0F)));
   }
}
